services:
  # dynamodb-local:
  #   image: amazon/dynamodb-local:latest
  #   container_name: dynamodb-local
  #   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./docker/dynamodb:/home/dynamodblocal/data
  #   working_dir: /home/dynamodblocal

  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   container_name: api
  #   ports:
  #     - "5201:5201"
  #   environment:
  #     - AWS__ServiceURL=http://dynamodb-local:8000
  #     - AWS__AccessKey=fakeMyKeyId
  #     - AWS__SecretKey=fakeSecretAccessKey
  #   depends_on:
  #     - dynamodb-local
  #   restart: always

  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
