services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - rede-interna

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - AWS__ServiceURL=http://dynamodb-local:8000
      - AWS__AccessKey=fakeMyKeyId
      - AWS__SecretKey=fakeSecretAccessKey
    depends_on:
      - dynamodb-local
    networks:
      - rede-interna
    restart: always

  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - rede-interna
    restart: always

networks:
  rede-interna:
    driver: bridge
    name: minha-rede-interna
